test:
  paginated-objects-per-page:
    annotation-documents: 10
    projects: 10
    raw-data: 10
    statistics: 10
  annotation-interface:
    container-class-name: annotation-interface
  timeouts:
    annotation-document-edit-time: 5
    url-response-checker: 3

development:
  paginated-objects-per-page:
    annotation-documents: 10
    projects: 10
    raw-data: 10
    statistics: 10
  annotation-interface:
    container-class-name: annotation-interface
  timeouts:
    annotation-document-edit-time: 5
    url-response-checker: 3

production:
  paginated-objects-per-page:
    annotation-documents: 10
    projects: 10
    raw-data: 10
    statistics: 10
  annotation-interface:
    container-class-name: annotation-interface
  timeouts:
    annotation-document-edit-time: 5
    url-response-checker: 20
