IrresponsibleModule:
  enabled: false
NestedIterators:
  max_allowed_nesting: 2
TooManyStatements:
  max_statements: 10
TooManyMethods:
  max_methods: 25
UncommunicativeModuleName:
  accept:
    - !ruby/regexp /V[0-9]+/
